# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hw0AenJ-7F3SAAnNM5hBaeBb-qVtD853
"""

import requests
from transformers import pipeline

# 리뷰 가져오기 (30개)
def fetch_reviews(appid, count):
    url = f"https://store.steampowered.com/appreviews/{appid}"
    params = {
        "json": 1,
        "language": "english",
        "filter": "recent",
        "num_per_page": count,
        "purchase_type": "all"
    }
    try:
        response = requests.get(url, params=params, timeout=10)
        data = response.json()
        reviews = [review['review'] for review in data.get("reviews", []) if 'review' in review]
        return reviews
    except Exception as e:
        print("[ERROR] Failed to fetch reviews:", e)
        return []

# 리뷰 요약 (T5 사용)
def summarize_reviews(reviews):
    if not reviews:
        return "No reviews available to summarize."

    text = " ".join(reviews)
    text = text[:1000]


    input_text = "summarize: " + text


    summarizer = pipeline("summarization", model="t5-small", tokenizer="t5-small")
    summary = summarizer(input_text, max_length=50, min_length=10, do_sample=False)
    return summary[0]['summary_text']


if __name__ == "__main__":
    appid = "1061090"  # 가져올 리뷰 gameid
    reviews = fetch_reviews(appid, count=30)
    print(f"[DEBUG] 가져온 리뷰 수: {len(reviews)}")

    summary = summarize_reviews(reviews)
    print("\n[Summary]")
    print(summary)